defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/pi0@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-1
    env: 2-2
    rollout: 3-3

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "dagger_sft_openpi_libero_spatial"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1
  
  only_eval: False
  val_check_interval: 2
  save_interval: 200

algorithm:
  expert_intervention_rate: 0.12 # init beta
  expert_intervention_rate_schedule: "constant"  # 选项: "constant", "linear", "exponential", "cosine"
  expert_intervention_rate_min: 0.02  # min beta
  expert_intervention_rate_decay_steps: 1000  # 从初始值衰减到最小值的 rollout epoch 数量
  expert_intervention_rate_decay_factor: 0.9  # 指数调度衰减因子 (仅当 schedule="exponential" 时使用)
  only_save_intervened: True  # 如果为 True, 只保存专家干预的步骤
  save_expert_predictions: True  # 如果为 True, 专家模型将在 rollout 期间为所有状态预测动作 (即使实际 rollout 使用的是基础模型), 并保存这些预测以供训练
  
  rollout_epoch: 1
  eval_rollout_epoch: 1
  
  update_epoch: 1
  use_fixed_reset_state_ids: False
  group_size: 1
  
  replay_buffer_capacity: 100000
  min_buffer_size: 10
  
  adv_type: gae
  loss_type: embodied_sac
  loss_agg_func: "token-mean"
  
  bootstrap_type: always
  gamma: 0.8
  tau: 0.01
  auto_entropy_tuning: True
  alpha_type: softplus
  initial_alpha: 0.01
  target_entropy: -4
  alpha_lr: 3.0e-4
  target_update_freq: 1
  agg_q: min
  
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: 7
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  train:
    total_num_envs: 2
    auto_reset: True
    ignore_terminations: True
    use_fixed_reset_state_ids: False
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
  
  eval:
    total_num_envs: 2
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
    use_fixed_reset_state_ids: True
    group_size: 1
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  model_dir: ""
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/mnt/project_rlinf/chenkang/openpi-main/checkpoints/sft/pi0_libero/all_patch_3/10000"
    precision: ${actor.model.precision}

  expert_model:
    model_path: "/mnt/project_rlinf/chenkang/openpi-main/checkpoints/sft/pi0_libero_130_fullshot/full_sft_pi0_libero_130_fullshot/30000"
    precision: ${actor.expert_model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"

  micro_batch_size: 32
  global_batch_size: 512
  seed: 1234
  enable_offload: False

  model:
    model_name: "openpi"
    model_path: "/mnt/project_rlinf/chenkang/openpi-main/checkpoints/sft/pi0_libero/all_patch_3/10000"
    action_dim: 7
    
    precision: "32"
    add_value_head: True
    add_q_head: True

  expert_model:
    model_name: "openpi"
    model_path: "/mnt/project_rlinf/chenkang/openpi-main/checkpoints/sft/pi0_libero_130_fullshot/full_sft_pi0_libero_130_fullshot/30000"
    action_dim: 7
    
    precision: "32"
    add_value_head: True
    add_q_head: True

  optim:
    lr: 7.91e-6
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    weight_decay: 0.01
    clip_grad: 1.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
